version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=todolist
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306