version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$$MYSQL_DATABASE9
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306